import json, os

COLOR = "#a6e3a1"
OUTDIR = "./physiotherapy"
os.makedirs(OUTDIR, exist_ok=True)

def e(en, ru, ex_en, ex_ru, note=""):
    return {"en": en, "ru": ru, "example_en": ex_en, "example_ru": ex_ru, "note": note, "image": ""}

anatomy = {
    "intro": "STRUCTURES and anatomical landmarks referenced in physiotherapy and occupational therapy sessions.",
    "reading": "Physiotherapy sessions involve detailed discussion of the musculoskeletal system: joints, bones, muscles, tendons, and ligaments throughout the body. Spinal anatomy — broken into cervical, thoracic, lumbar, sacral, and coccygeal regions — is especially common in PT communication. Interpreters also frequently encounter shoulder anatomy, limb structures, and post-amputation terms such as the residual limb.",
    "color": COLOR,
    "terms": [
        e("Intervertebral disc", "Межпозвоночный диск", "The MRI showed a damaged intervertebral disc in the lumbar region.", "МРТ показало повреждённый межпозвоночный диск в поясничной области.", "Also called 'spinal disc' — both terms appear in source; merged"),
        e("Hip", "Бедро", "She feels pain in the hip when walking.", "При ходьбе у неё болит бедро."),
        e("Hip joint", "Бедренный сустав", "The hip joint connects the leg to the pelvis.", "Бедренный сустав соединяет ногу с тазом."),
        e("Heel", "Пятка", "He has sharp pain in the heel when taking a step.", "При шаге у него острая боль в пятке.", "Source: 'a heel' and 'a heel of the leg' — merged"),
        e("Lower back", "Поясница", "The lower back pain has been present for three weeks.", "Боль в пояснице сохраняется уже три недели."),
        e("Rotator cuff", "Вращающая манжета плеча", "The rotator cuff stabilizes the shoulder joint.", "Вращающая манжета плеча стабилизирует плечевой сустав.", "Appears twice in source — merged"),
        e("Thigh muscles", "Мышцы бедра", "Strengthening the thigh muscles helps protect the knee.", "Укрепление мышц бедра помогает защитить колено."),
        e("Ankle", "Лодыжка / голеностопный сустав", "He sprained his ankle during the fall.", "Он вывихнул лодыжку при падении.", "Source typos: 'лодышка', 'голонестопный', 'щиколодка' — corrected; duplicates merged"),
        e("Torso", "Туловище", "Core exercises strengthen the muscles of the torso.", "Упражнения для кора укрепляют мышцы туловища."),
        e("Feet", "Ступни", "Please place both feet flat on the floor.", "Поставьте обе ступни ровно на пол."),
        e("Collarbone (clavicle)", "Ключица", "She fractured her collarbone in the accident.", "В аварии она сломала ключицу."),
        e("Shin", "Голень", "The shin runs from the knee to the ankle.", "Голень расположена между коленом и лодыжкой.", "Source: 'shin' and 'голень' (reversed) — merged"),
        e("Motor centers", "Двигательные центры", "A stroke can damage the motor centers in the brain.", "Инсульт может повредить двигательные центры мозга."),
        e("Tendon", "Сухожилие", "The tendon connects the muscle to the bone.", "Сухожилие соединяет мышцу с костью.", "Source: 'сухожилие ; tendon' (reversed) — merged"),
        e("Ligaments", "Связки", "Ligaments connect bones to other bones at the joints.", "Связки соединяют кости друг с другом в суставах.", "Source: 'связки ; ligaments' (reversed) — merged"),
        e("Humerus (arm bone)", "Плечевая кость", "The humerus extends from the shoulder to the elbow.", "Плечевая кость простирается от плеча до локтя.", "Source: 'arm bone' (patient term) and 'arm bone, humerus' — merged; typos 'плеевоая' corrected"),
        e("Ulna", "Локтевая кость", "The ulna runs along the inner forearm.", "Локтевая кость проходит вдоль внутренней части предплечья."),
        e("Radius", "Лучевая кость", "The radius is on the thumb side of the forearm.", "Лучевая кость расположена со стороны большого пальца предплечья."),
        e("Deltoid muscles", "Дельтовидные мышцы", "The deltoid muscles cover the shoulder and assist in lifting the arm.", "Дельтовидные мышцы охватывают плечо и помогают поднимать руку.", "Source typos: 'deltoid muslces', 'делтавидные' — corrected"),
        e("Shoulder blade (scapula)", "Лопатка", "Scapular retraction involves squeezing the shoulder blades together.", "Сведение лопаток предполагает сближение лопаток.", "Source: 'shoulder blade' and 'scapula' are the same structure — merged"),
        e("Ball and socket joint", "Шаровидный сустав (головка и впадина)", "The shoulder is a ball and socket joint allowing a wide range of motion.", "Плечо является шаровидным суставом, обеспечивающим широкий диапазон движений."),
        e("Armpit area (axilla)", "Подмышечная впадина", "There is some swelling in the armpit area.", "В подмышечной впадине есть небольшой отёк."),
        e("Head of the humerus", "Головка плечевой кости", "The head of the humerus fits into the shoulder socket.", "Головка плечевой кости входит в плечевую впадину.", "Source: 'head of arm bone' (no Russian) and 'head of the arm bone' — merged using complete entry"),
        e("Shoulder socket (glenoid fossa)", "Плечевая впадина (суставная ямка)", "The shoulder socket is shallow, allowing mobility but increasing dislocation risk.", "Плечевая впадина неглубокая, что обеспечивает подвижность, но увеличивает риск вывиха."),
        e("Pectoral muscles (pecs)", "Грудные мышцы", "The pectoral muscles are used in pushing movements.", "Грудные мышцы задействованы в толкающих движениях.", "Source: 'pecks' (typo), 'грудные мышци' — corrected"),
        e("Spine", "Позвоночник", "The spine consists of 33 vertebrae divided into five regions.", "Позвоночник состоит из 33 позвонков, разделённых на пять отделов."),
        e("Cervical spine", "Шейный отдел позвоночника (7 позвонков)", "The cervical spine supports the head and allows neck movement.", "Шейный отдел позвоночника поддерживает голову и обеспечивает движения шеи.", "Source: 'cervical' and 'шейный отдел ; cervical spine' (redundant) — merged"),
        e("Thoracic spine", "Грудной отдел позвоночника (12 позвонков)", "The thoracic spine connects to the rib cage.", "Грудной отдел позвоночника соединяется с грудной клеткой.", "Source: 'thoratic' — corrected to 'thoracic'"),
        e("Lumbar spine", "Поясничный отдел позвоночника (5 позвонков)", "Most lower back pain originates in the lumbar spine.", "Большинство болей в пояснице возникает в поясничном отделе позвоночника.", "Source: 'пояничный' — corrected"),
        e("Sacral spine (sacrum)", "Крестцовый отдел позвоночника (5 позвонков)", "The sacral spine connects the spinal column to the pelvis.", "Крестцовый отдел позвоночника соединяет позвоночный столб с тазом."),
        e("Coccygeal spine (coccyx)", "Копчиковый отдел позвоночника (3–5 позвонков)", "The coccygeal spine is the lowest section of the vertebral column.", "Копчиковый отдел — самая нижняя часть позвоночного столба."),
        e("Tailbone (coccyx)", "Копчик", "She bruised her tailbone in the fall.", "При падении она ушибла копчик.", "Informal term for the coccyx"),
        e("Phalanx (finger or toe bone)", "Фаланга", "Each finger has three phalanges except the thumb.", "Каждый палец руки имеет три фаланги, кроме большого."),
        e("Chest wall", "Стенка грудной клетки", "Breathing exercises help expand the chest wall.", "Дыхательные упражнения помогают расширить стенку грудной клетки.", "Appears twice — merged"),
        e("Sternum (breastbone)", "Грудина", "The sternum is the flat bone at the center of the chest.", "Грудина — плоская кость в центре грудной клетки.", "Source: 'sterna' — corrected"),
        e("Knee menisci (meniscal cartilage)", "Мениски колена", "The menisci cushion the knee joint during movement.", "Мениски амортизируют коленный сустав при движении.", "Source: 'миниски' — corrected"),
        e("Residual limb", "Остаточная конечность", "The prosthetist measured the residual limb for the fitting.", "Протезист измерил остаточную конечность для примерки."),
    ]
}

conditions = {
    "intro": "CONDITIONS, symptoms, and clinical presentations encountered in physiotherapy and occupational therapy.",
    "reading": "PT and OT sessions cover a broad range of musculoskeletal, neurological, and functional conditions — from disc herniations and fractures to balance disorders and post-amputation care. Interpreters must handle both clinical diagnostic terms and everyday patient language describing pain, mobility limitations, and movement difficulties.",
    "color": COLOR,
    "terms": [
        e("Herniated disc", "Межпозвоночная грыжа", "He has a herniated disc pressing on the nerve.", "У него межпозвоночная грыжа, давящая на нерв.", "Source: 'herneated disc' — corrected"),
        e("Radiating pain", "Боль, отдающая в... / боль поднимается", "The pain radiates from the lower back down to the leg.", "Боль отдаёт из поясницы вниз по ноге.", "Merged: 'the pain goes up' and 'pain radiates to'"),
        e("Injury (general)", "Травма", "She is recovering from a shoulder injury.", "Она восстанавливается после травмы плеча."),
        e("Femur fracture", "Перелом бедренной кости", "A femur fracture requires careful rehabilitation.", "Перелом бедренной кости требует тщательной реабилитации."),
        e("Femur neck fracture", "Перелом шейки бедренной кости", "Femur neck fractures are common in elderly patients with osteoporosis.", "Переломы шейки бедренной кости часто встречаются у пожилых пациентов с остеопорозом."),
        e("Malunion (bones healed incorrectly)", "Кости зажили неправильно / неправильное срастание", "If the bones healed incorrectly, surgery may be needed.", "Если кости зажили неправильно, может потребоваться операция.", "Appears twice in source — merged"),
        e("Development anomalies", "Пороки развития", "The child has development anomalies affecting posture.", "У ребёнка пороки развития, влияющие на осанку."),
        e("Cognitive impairments", "Когнитивные нарушения", "Cognitive impairments can make following PT instructions difficult.", "Когнитивные нарушения могут затруднить выполнение инструкций физиотерапевта."),
        e("Balance disorder", "Нарушение равновесия", "The patient has a balance disorder and is at risk of falling.", "У пациента нарушение равновесия, что увеличивает риск падения.", "Source: 'a balance (med)' — expanded to full clinical term"),
        e("Rotator cuff injury", "Травма вращающей манжеты плеча", "She came in with a rotator cuff injury from lifting.", "Она поступила с травмой вращающей манжеты плеча от подъёма тяжестей."),
        e("Fracture (general)", "Перелом", "The X-ray confirmed a fracture in the wrist.", "Рентген подтвердил перелом запястья."),
        e("Non-displaced fracture", "Перелом без смещения", "A non-displaced fracture means the bone cracked but did not shift.", "Перелом без смещения означает, что кость треснула, но не сдвинулась."),
        e("Vertebral fracture", "Перелом позвонка / трещина в позвонке", "A vertebral fracture can compress the spinal cord.", "Перелом позвонка может вызвать компрессию спинного мозга."),
        e("Muscle strain", "Растяжение мышцы", "He has a muscle strain in the lower back from lifting.", "У него растяжение мышцы поясницы от подъёма тяжестей.", "Merged: 'a strain', 'strain in the back', 'strained a muscle', 'muscle strains'"),
        e("Muscle tightness", "Напряжённые / затянутые мышцы", "Her muscles have tightened since the injury.", "После травмы её мышцы затянулись.", "Merged: 'muscles have tightened' and 'to have a tight muscle'"),
        e("To trip / tripped", "Споткнуться / споткнулся", "He tripped on the stairs and hurt his knee.", "Он споткнулся на лестнице и ушиб колено.", "Merged: 'tripped' and 'to trip'"),
        e("To fall", "Падать / упасть", "She fell getting out of bed in the morning.", "Утром она упала, вставая с кровати."),
        e("Osteoporosis", "Остеопороз", "Osteoporosis makes bones fragile and prone to fractures.", "Остеопороз делает кости хрупкими и склонными к переломам."),
        e("Osteopenia", "Остеопения", "Osteopenia is a lower-than-normal bone density, a precursor to osteoporosis.", "Остеопения — это сниженная плотность костей, предшественник остеопороза."),
        e("Bone thinning", "Истончение костей", "Bone thinning is an early sign of osteopenia.", "Истончение костей является ранним признаком остеопении.", "Source: 'утоньщение' — corrected"),
        e("Scar tissue", "Рубцовая ткань", "Scar tissue from surgery has limited her shoulder movement.", "Рубцовая ткань после операции ограничила движение плеча."),
        e("Moderate shortness of breath", "Умеренная одышка", "The patient became moderately out of breath after walking one block.", "После ходьбы на один квартал у пациента появилась умеренная одышка."),
        e("Trembling / shaking hands", "Руки трясутся", "His hands have been shaking since the neurological episode.", "С момента неврологического эпизода у него трясутся руки."),
        e("Bone-deep pain", "Пронизывающая до костей боль", "She described the pain as a deep, bone-rattling ache.", "Она описала боль как глубокую, пронизывающую до костей."),
        e("Disc protrusion", "Межпозвоночная протрузия", "A disc protrusion is less severe than a full herniation.", "Протрузия диска менее серьёзна, чем полная грыжа."),
        e("Sensory deficit", "Дефицит чувствительности", "The patient has a sensory deficit in the right leg.", "У пациента дефицит чувствительности в правой ноге."),
        e("Skin breakdown", "Нарушение целостности кожи", "Prolonged pressure causes skin breakdown in immobile patients.", "Длительное давление вызывает нарушение целостности кожи у малоподвижных пациентов."),
        e("Pressure sores / pressure injury", "Пролежни / травма от давления", "Frequent repositioning prevents pressure sores.", "Частая смена положения предотвращает пролежни.", "Merged: 'preassure sores' (typo), 'pressure injury', 'пролежни'"),
        e("Unsteady on feet / unsteadiness", "Неустойчивость / ноги проваливаются", "She feels unsteady on her feet after standing up quickly.", "После быстрого вставания она чувствует неустойчивость.", "Merged: 'unsteadiness' (2x), 'unsteady on feet', 'ноги проваливаются'"),
        e("Vertebral compression / spine collapse", "Проседание позвоночника / компрессия позвонков", "Osteoporosis can lead to vertebral compression over time.", "Остеопороз может со временем привести к компрессии позвонков.", "Source: 'spine collapses' appears 3 times — merged"),
        e("Spinal curvature (general)", "Искривление позвоночника", "The X-ray showed an abnormal spinal curvature.", "Рентген показал патологическое искривление позвоночника."),
        e("Kyphosis", "Кифоз", "Kyphosis causes an exaggerated forward curve of the upper back.", "Кифоз вызывает чрезмерный изгиб позвоночника вперёд в верхней части спины."),
        e("Inward / outward spinal curve", "Внутренний / наружный изгиб позвоночника", "The physiotherapist noted an outward curve at the thoracic level.", "Физиотерапевт отметил наружный изгиб на уровне грудного отдела."),
        e("Apex of the curve", "Верхушка / вершина дуги искривления", "The apex of the curve is at the L3 vertebra.", "Верхушка дуги искривления находится на уровне позвонка L3."),
        e("Stooped posture / bent-over gait", "Сгорбленная осанка / сгорбленная походка", "Kyphosis often results in a stooped posture and bent-over gait.", "Кифоз часто приводит к сгорбленной осанке и согнутой походке.", "Merged: 'Walk with a stoop', 'Bent-over gait', 'to stoop'"),
        e("Pins and needles sensation", "Ощущение покалывания / мурашки", "She feels pins and needles in her feet when standing up.", "Когда она встаёт, она ощущает покалывание в ступнях."),
        e("Stiffness", "Скованность", "Morning stiffness in the joints is common with arthritis.", "Утренняя скованность в суставах типична при артрите.", "Appears twice — merged; 'too stiff' folded in"),
        e("Musculoskeletal dysfunction", "Нарушение функции опорно-двигательного аппарата", "Musculoskeletal dysfunction can affect a patient's daily activities.", "Нарушение функции опорно-двигательного аппарата может влиять на повседневную жизнь пациента.", "Source: 'muslce skeletal function' (2x, typo) — corrected and merged"),
        e("Osteoarthritis", "Остеоартрит", "Osteoarthritis is a degenerative joint disease common in older adults.", "Остеоартрит — дегенеративное заболевание суставов, распространённое у пожилых людей."),
        e("Primary osteoarthritis", "Первичный остеоартрит", "Primary osteoarthritis develops with age without an underlying cause.", "Первичный остеоартрит развивается с возрастом без конкретной причины."),
        e("Back seized up", "Спину схватило / спину прихватило", "He says his back seized up when he bent over.", "Он говорит, что когда он наклонился, спину схватило.", "Colloquial patient expression — source: 'спину хватает'"),
        e("Scraped / skinned knee", "Ободрал коленку / ссадина на колене", "The child skinned his knee on the playground.", "Ребёнок ободрал коленку на игровой площадке.", "Informal patient/caregiver expression"),
        e("Joint hypermobility", "Гипермобильность сустава / сустав выгибается назад", "She mentioned that her joint can bend backwards a little.", "Она отметила, что её сустав немного выгибается назад."),
        e("Torn ligaments", "Разрыв связок", "He tore the ligaments in his knee during the game.", "Он порвал связки колена во время игры.", "Source: 'to torn the ligaments' — grammatical error corrected"),
        e("Leg fell asleep (paresthesia)", "Нога онемела / отсидела ногу", "She said her leg fell asleep after sitting for an hour.", "Она сказала, что нога онемела после часа сидения.", "Colloquial patient phrase; source: 'отсидела ногу'"),
        e("Muscle spasm", "Судорога / мышцу сводит", "He woke up with a muscle spasm in his calf.", "Он проснулся с судорогой в икроножной мышце.", "Merged: 'muscle seized up' and 'muscle spasm'"),
        e("Fatigue / muscle fatigue", "Усталость / мышечная усталость", "He feels fatigued after only short periods of exercise.", "Он устаёт после коротких периодов физической нагрузки.", "Merged: 'muscle fatique', 'it will fatique your muscles', 'to feel fatigued'; typos corrected"),
        e("Motor control impairment", "Нарушение двигательного контроля", "Stroke can cause motor control impairment on one side of the body.", "Инсульт может вызвать нарушение двигательного контроля с одной стороны тела."),
        e("Dizziness / wooziness", "Головокружение / дурно", "She felt woozy and unsteady after standing up too quickly.", "После слишком быстрого вставания ей стало дурно и неустойчиво.", "Merged: 'woozy' and 'wooziness'"),
        e("Muscle tension", "Мышечное напряжение", "Chronic muscle tension in the neck can cause headaches.", "Хроническое мышечное напряжение в шее может вызывать головные боли."),
        e("Dislocation", "Вывих", "The shoulder dislocation was reduced in the emergency room.", "Вывих плеча был вправлен в отделении неотложной помощи.", "Merged: 'dislocation', 'dislocation and loosening' (2x); see also 'to dislocate' in Procedures"),
        e("Hardware loosening", "Расшатывание компонентов / конструкции", "Hardware loosening may require revision surgery.", "Расшатывание компонентов может потребовать ревизионной операции.", "Appears twice (one with empty Russian) — merged"),
        e("Joint contractures", "Контрактуры суставов", "Joint contractures limit the range of motion in the affected joint.", "Контрактуры ограничивают объём движений в поражённом суставе.", "Source: 'контракуты' — corrected"),
        e("ALS (amyotrophic lateral sclerosis)", "БАС (боковой амиотрофический склероз)", "ALS progressively weakens the muscles throughout the body.", "БАС постепенно ослабляет мышцы по всему телу."),
        e("Lymphedema", "Лимфедема / лимфатический отёк", "Lymphedema causes swelling due to a build-up of lymph fluid.", "Лимфедема вызывает отёк из-за накопления лимфатической жидкости."),
        e("Lower extremity lymphedema", "Лимфедема нижних конечностей", "She developed lower extremity lymphedema after cancer treatment.", "У неё развилась лимфедема нижних конечностей после лечения рака."),
        e("Orthostatic hypertension", "Ортостатическая гипертония", "Orthostatic hypertension is a rise in blood pressure upon standing.", "Ортостатическая гипертония — это повышение артериального давления при вставании.", "Note: orthostatic hypotension (drop in BP) is more common clinically — verify which is intended"),
        e("Sprain / twisted finger", "Растяжение / подвернуть палец", "She sprained her finger catching the ball.", "Она подвернула палец, ловя мяч."),
        e("Limping", "Хромать / хромота", "He has been limping since the surgery.", "Он хромает с момента операции."),
        e("Canal stenosis (spinal)", "Стеноз / сужение позвоночного канала", "Spinal canal stenosis can cause pain and weakness in the legs.", "Стеноз позвоночного канала может вызывать боль и слабость в ногах."),
        e("Bone alignment", "Расположение / выравнивание кости", "The surgeon checked the bone alignment after reduction.", "Хирург проверил положение кости после вправления."),
        e("Bone healing", "Срастание кости", "Bone healing can take six to eight weeks for minor fractures.", "Срастание кости при небольших переломах может занять от шести до восьми недель."),
        e("Foreign body", "Инородное тело", "An X-ray was ordered to rule out a foreign body in the joint.", "Был назначен рентген для исключения инородного тела в суставе."),
        e("Stamina / endurance", "Выносливость", "We will work on building stamina throughout the program.", "Мы будем работать над повышением выносливости в ходе всей программы.", "Merged: 'stamina' and 'endurance' (both in Others section)"),
        e("Disability", "Инвалидность", "The patient applied for disability benefits after the injury.", "Пациент подал заявление на получение пособия по инвалидности после травмы.", "From Others section"),
        e("Warning signs / red flags", "Тревожные признаки / красные флаги", "Tell your therapist immediately if you notice any warning signs.", "Немедленно сообщите терапевту, если заметите тревожные признаки.", "From Others section"),
    ]
}

devices = {
    "intro": "DEVICES, mobility aids, adaptive equipment, and home modifications used in physiotherapy and occupational therapy.",
    "reading": "PT and OT involve a wide range of assistive devices — from mobility aids like canes, crutches, and wheelchairs to post-surgical supports such as casts, splints, and slings. OT also includes home modification equipment: grab bars, raised toilet seats, reachers, and shower chairs. These terms arise often in discharge planning and home safety discussions.",
    "color": COLOR,
    "terms": [
        e("Cane", "Трость", "He uses a cane to support his weight when walking.", "Он использует трость для поддержки при ходьбе."),
        e("Crutches", "Костыли", "She was given crutches to use until the fracture heals.", "Ей выдали костыли до заживления перелома.", "Source: 'cruthces' (typo), duplicate — merged and corrected"),
        e("Sling", "Повязка / поддерживающая повязка", "Keep your arm in the sling for the next three weeks.", "Держите руку в повязке следующие три недели.", "Merged: 'a sling' and 'to be in a sling'"),
        e("Cast", "Гипс", "The cast will be on for six weeks.", "Гипс будет наложен на шесть недель.", "Appears 3 times in source — merged"),
        e("Boot (orthopedic)", "Ортопедический ботинок", "She is in a boot to immobilize the ankle while it heals.", "Она носит ортопедический ботинок для фиксации лодыжки во время заживления."),
        e("Wheelchair", "Инвалидная коляска", "He will need a wheelchair until he can walk again.", "Ему потребуется инвалидная коляска до восстановления ходьбы.", "Merged: 'a wheelchair' and 'to be in a wheelchair'"),
        e("Splint", "Шина", "A splint was applied to stabilize the injured wrist.", "Шина была наложена для стабилизации повреждённого запястья.", "Appears 3 times — merged"),
        e("Grab bars", "Поручни (в душе / у унитаза)", "Grab bars in the shower reduce the risk of falls.", "Поручни в душе снижают риск падения."),
        e("Surgical rods", "Стержни (хирургические)", "The surgeon used rods to stabilize the fractured spine.", "Хирург использовал стержни для стабилизации сломанного позвоночника.", "Appears twice — merged"),
        e("Heat pads", "Грелки", "Heat pads can relax tight muscles before a session.", "Грелки помогают расслабить напряжённые мышцы перед занятием."),
        e("Compression stockings", "Компрессионные чулки", "Compression stockings help prevent blood clots in the legs.", "Компрессионные чулки помогают предотвратить образование тромбов в ногах."),
        e("Metal plates, pins and rods", "Металлические пластины, спицы и стержни", "The fracture was fixed with metal plates, pins, and rods.", "Перелом был зафиксирован металлическими пластинами, спицами и стержнями.", "Source: 'металические' — corrected"),
        e("Brace / arm brace", "Корсет / фиксатор руки", "The brace supports the lower back during activity.", "Корсет поддерживает поясницу во время физической нагрузки.", "Source: 'карсет' — corrected; merged 'a brace' and 'a brace on the arm'"),
        e("Leg rest", "Подставка для ног", "A leg rest helps elevate the limb and reduce swelling.", "Подставка для ног помогает приподнять конечность и уменьшить отёк."),
        e("Shower chair", "Стул для душа", "A shower chair allows the patient to bathe safely.", "Стул для душа позволяет пациенту безопасно принимать душ."),
        e("Railings", "Перила", "Railings along the hallway help him walk without falling.", "Перила вдоль коридора помогают ему ходить без риска падения."),
        e("Straps", "Ремни (удерживающие)", "The straps on the brace keep it in place during exercise.", "Ремни на фиксаторе удерживают его на месте во время упражнений."),
        e("Contraption / adaptive device (informal)", "Приспособление", "The therapist brought a contraption to help with dressing.", "Терапевт принёс приспособление, помогающее одеваться.", "General/informal term for an adaptive device whose name is not known"),
        e("Wheelchair ramp", "Пандус для инвалидной коляски", "A wheelchair ramp was installed at the entrance.", "У входа был установлен пандус для инвалидной коляски."),
        e("Walk-in shower", "Душевая кабина без поддона", "A walk-in shower eliminates the need to step over a threshold.", "Душевая кабина без поддона исключает необходимость перешагивать порог.", "Appears twice — merged"),
        e("Step-over tub with shower", "Ванна с душем (через бортик)", "A step-over tub requires the patient to lift the leg over the edge.", "Ванна через бортик требует подъёма ноги через бортик."),
        e("Raised toilet seat / higher toilet", "Приподнятое сиденье для унитаза", "A raised toilet seat reduces hip strain when sitting down.", "Приподнятое сиденье уменьшает нагрузку на бёдра при садении.", "Merged: 'raised toilet seat' and 'higher toilet'"),
        e("Bidet", "Биде", "A bidet reduces the need for bending and twisting in the bathroom.", "Биде снижает необходимость наклоняться и поворачиваться в ванной.", "Source: 'Bidete' — corrected"),
        e("Recliner", "Кресло с откидной спинкой", "A recliner lets the patient rest comfortably with legs elevated.", "Кресло с откидной спинкой позволяет пациенту отдыхать с поднятыми ногами.", "Merged: 'recliener' (typo) and 'recliner'"),
        e("Handheld shower", "Ручной душ", "A handheld shower allows bathing without moving around.", "Ручной душ позволяет мыться без лишних движений."),
        e("Arm crank", "Ручной велотренажёр / вращение руками", "The arm crank machine provides upper body cardio training.", "Ручной велотренажёр обеспечивает кардионагрузку для верхней части тела."),
        e("Dumbbells", "Гантели", "Light dumbbells are used for shoulder strengthening exercises.", "Лёгкие гантели используются для упражнений на укрепление плеч."),
        e("Reachers / grabbers", "Захватные устройства / манипуляторы", "Reachers help patients pick up objects without bending.", "Захватные устройства помогают пациентам поднимать предметы, не наклоняясь.", "Source lists separately; functionally same category — merged"),
        e("Armrest", "Подлокотник / боковая опора", "The armrest helps the patient push up from the chair.", "Подлокотник помогает пациенту опереться и встать со стула."),
        e("Cervical collar (neck brace)", "Шейный ортез / воротник на шее", "She must wear the cervical collar for six weeks.", "Ей нужно носить шейный ортез шесть недель."),
        e("Shrinker sock", "Компрессионный носок (для остаточной конечности)", "A shrinker sock is worn on the residual limb to reduce swelling.", "Компрессионный носок надевается на остаточную конечность для уменьшения отёка."),
    ]
}

pharmacology = {
    "intro": "PHARMACOLOGICAL agents mentioned in physiotherapy and occupational therapy communication.",
    "reading": "Pharmacology plays a limited direct role in PT and OT sessions, though muscle relaxants are commonly prescribed alongside physiotherapy for conditions involving spasticity, spasm, or severe muscle tightness.",
    "color": COLOR,
    "terms": [
        e("Muscle relaxant", "Миорелаксант / мышечный релаксант", "The doctor prescribed a muscle relaxant to reduce spasm before therapy.", "Врач назначил миорелаксант для уменьшения спазма перед терапией."),
    ]
}

procedures = {
    "intro": "PROCEDURES, exercises, body positions, movement instructions, and assessment terms used in physiotherapy and occupational therapy.",
    "reading": "PT and OT generate a high volume of procedural language: assessments, surgical procedures, therapeutic exercises, ADL (activities of daily living), and precise movement commands. Interpreters must convey exact body position instructions, exercise names, and directional cues accurately. This section also includes healthcare roles relevant to the PT/OT team.",
    "color": COLOR,
    "terms": [
        # ── ASSESSMENTS ──────────────────────────────────────────
        e("Bone density scan (DEXA scan)", "Денситометрия / рентген плотности костей", "The DEXA scan measures bone mineral density.", "Денситометрия измеряет минеральную плотность костей.", "Merged: 'bone density test', 'bone density xray', 'DEXA scan', 'bone mineral density test' — DEXA is the standard clinical term"),
        e("Cognitive assessment", "Когнитивное обследование", "The therapist completed a cognitive assessment before starting the program.", "Терапевт провёл когнитивное обследование перед началом программы."),
        e("Range of motion", "Диапазон движения / подвижность суставов", "She has reduced range of motion in the shoulder.", "У неё снижен диапазон движения в плечевом суставе."),
        e("Alignment of the legs", "Положение / выравнивание ног", "The physiotherapist assessed the alignment of the legs.", "Физиотерапевт оценил положение ног."),
        # ── CLINICAL / SURGICAL PROCEDURES ───────────────────────
        e("Endoprosthetics / joint replacement", "Эндопротезирование (замена сустава)", "She underwent joint replacement surgery on her hip.", "Ей выполнили операцию по замене тазобедренного сустава."),
        e("Reverse shoulder replacement", "Реверсивное эндопротезирование плечевого сустава", "Reverse shoulder replacement is used when the rotator cuff is severely damaged.", "Реверсивное эндопротезирование плечевого сустава применяется при тяжёлом повреждении вращательной манжеты."),
        e("Rotator cuff repair", "Восстановление вращательной манжеты плеча", "Rotator cuff repair is followed by several weeks of PT.", "После восстановления вращательной манжеты плеча необходимо несколько недель физиотерапии."),
        e("Kyphoplasty", "Кифопластика", "Kyphoplasty is a minimally invasive procedure for spinal compression fractures.", "Кифопластика — малоинвазивная процедура при компрессионных переломах позвоночника."),
        e("Bone cement", "Костный цемент", "Bone cement was used to stabilize the fractured vertebra.", "Костный цемент был использован для стабилизации сломанного позвонка."),
        e("Irrigation of the joint", "Промывание сустава", "Irrigation of the joint removes debris and reduces inflammation.", "Промывание сустава удаляет воспалительные отложения."),
        e("Debridement of the shoulder", "Хирургическая обработка плечевого сустава", "Debridement removes damaged tissue from the shoulder joint.", "Хирургическая обработка удаляет повреждённые ткани из плечевого сустава."),
        e("To dislocate", "Вывихнуть / сместить (сустав)", "He dislocated his shoulder during the fall.", "Он вывихнул плечо при падении.", "Source: 'Вывихнуть, Смещать (сустав), Разъединить'"),
        e("Biocompatibility (material integration)", "Биосовместимость / приживаемость материала", "The implant was designed for high biocompatibility with the body.", "Имплантат был разработан с высокой биосовместимостью с тканями тела.", "Source: 'приживаться к телу ; biocompatability' — typo corrected"),
        e("Conservative treatment", "Консервативное лечение", "Conservative treatment includes physical therapy and pain management before surgery.", "Консервативное лечение включает физиотерапию и обезболивание перед операцией.", "From Others section"),
        e("Chiropractic treatment", "Лечение у хиропрактора", "She tried chiropractic treatment for her lower back pain.", "Она пробовала лечение у хиропрактора от боли в пояснице.", "Source: 'хиропарктора' — corrected; from Others section"),
        e("Speech therapy", "Речевая терапия / занятия с логопедом", "She attends speech therapy twice a week after the stroke.", "После инсульта она посещает речевую терапию дважды в неделю."),
        e("Verticalization", "Вертикализация", "Verticalization is the gradual process of getting a patient to an upright position.", "Вертикализация — постепенный процесс перевода пациента в вертикальное положение.", "Source: 'вертикализация' (no English given) — term added"),
        # ── BODY POSITIONS ───────────────────────────────────────
        e("Prone position", "Положение лёжа на животе", "Please turn over and lie in the prone position.", "Пожалуйста, перевернитесь и лягте на живот."),
        e("Supine position", "Положение лёжа на спине", "For this exercise, start in the supine position.", "Для этого упражнения начните в положении лёжа на спине."),
        e("Lateral position", "Положение лёжа на боку", "Turn to the lateral position to relieve pressure on your back.", "Повернитесь на бок, чтобы снять давление со спины."),
        e("Sitting position", "Положение сидя", "Maintain the sitting position during the exercise.", "Сохраняйте положение сидя во время упражнения."),
        e("Standing position", "Положение стоя", "Now perform the same movement in the standing position.", "Теперь выполните то же движение в положении стоя."),
        e("Kneeling position", "Положение на коленях", "Get into a kneeling position on the mat.", "Встаньте на колени на коврике."),
        # ── EXERCISES ────────────────────────────────────────────
        e("Core strengthening exercises", "Упражнения для укрепления мышц кора", "Core strengthening exercises help protect the spine.", "Упражнения для укрепления мышц кора помогают защитить позвоночник.", "Source: 'упражнение' — corrected to plural"),
        e("Strengthening exercises (general)", "Силовые / укрепляющие упражнения", "We will start with light strengthening exercises for the shoulder.", "Мы начнём с лёгких укрепляющих упражнений для плеча.", "Source: 'strengtheining exercises' — typo corrected"),
        e("Stretching", "Растяжка", "Stretching after exercise helps prevent muscle tightness.", "Растяжка после упражнений помогает предотвратить скованность мышц.", "Merged: 'stretching', 'to do stretching', 'stretch'"),
        e("Quad stretch", "Растяжка четырёхглавой мышцы", "Hold the quad stretch for thirty seconds on each leg.", "Удерживайте растяжку четырёхглавой мышцы по тридцать секунд на каждую ногу.", "Source: 'растяжка четырёхглавой мышцу' — corrected"),
        e("Toe crunches", "Сгибания пальцев ног", "Toe crunches help strengthen the small muscles of the foot.", "Сгибания пальцев ног укрепляют мелкие мышцы стопы.", "Source: 'toe crunhes' — typo corrected"),
        e("Deep squatting", "Глубокое приседание", "Avoid deep squatting until the knee is fully healed.", "Избегайте глубоких приседаний до полного восстановления колена."),
        e("Scapular retraction", "Сведение лопаток", "Perform scapular retraction by squeezing your shoulder blades together.", "Выполняйте сведение лопаток, сжимая лопатки вместе.", "Merged: 'scapular retraction' and 'to retract the shoulders'"),
        e("Scapular protraction", "Разведение лопаток", "Now protract the shoulders by pushing them forward.", "Теперь разведите лопатки, выдвигая плечи вперёд.", "Merged: 'to protract the shoulders'"),
        e("Internal rotation", "Внутреннее вращение", "Internal rotation of the shoulder is restricted after surgery.", "Внутреннее вращение плеча ограничено после операции."),
        e("Arms to the side", "Руки в стороны", "Slowly raise your arms to the side to shoulder height.", "Медленно поднимите руки в стороны до уровня плеч."),
        e("The rows (exercise)", "Тяга в наклоне", "The rows strengthen the upper back and rear shoulder muscles.", "Тяга в наклоне укрепляет верхнюю часть спины и задние мышцы плеч."),
        e("Low trap lift off", "Подъём рук для нижней порции трапеции", "The low trap lift off targets the lower trapezius muscle.", "Подъём рук для нижней порции трапеции прорабатывает нижнюю трапецию."),
        e("Tighten a muscle", "Напрячь мышцу", "Tighten the muscle and hold for five seconds.", "Напрягите мышцу и удерживайте пять секунд.", "Merged: 'tighten a muscle' and 'to tighten the muslce' (typo)"),
        e("Squeeze and release", "Сжать и отпустить", "Squeeze the ball and release — repeat ten times.", "Сожмите мяч и отпустите — повторите десять раз."),
        e("Bring knees out and in", "Разведите колени в стороны, затем сведите", "Bring your knees out and in slowly to work the hip muscles.", "Медленно разводите и сводите колени для проработки мышц бедра.", "Source: 'bring your knees out and in'"),
        e("Paired muscle relaxation", "Синхронное расслабление мышц", "Paired muscle relaxation involves tensing and then releasing muscle groups.", "Синхронное расслабление мышц предполагает напряжение и расслабление мышечных групп."),
        e("Muscle rub / massage", "Массировать / растирать мышцу", "I will rub your muscle to help loosen it before the exercise.", "Я помассирую вашу мышцу, чтобы расслабить её перед упражнением.", "Merged: 'to rub a muslce', 'i will rub your muslce' (typos corrected); 'have you tried rubbing' folded in as example context"),
        e("Keep neck / chin tucked", "Держать подбородок прижатым / нейтральное положение шеи", "Keep your chin tucked throughout the exercise.", "Удерживайте подбородок прижатым к груди во время упражнения.", "Merged: 'keep your neck tucked in' and 'keep ur chin tucked'"),
        # ── MOVEMENT COMMANDS ────────────────────────────────────
        e("To reposition / get repositioned", "Изменить / сменить положение тела", "We need to reposition you to prevent pressure sores.", "Нам нужно изменить ваше положение, чтобы предотвратить пролежни.", "Merged: 'to reposition' and 'to get repositioned'"),
        e("To sit up", "Сесть / сядьте ровно", "Now sit up slowly from the lying position.", "Теперь медленно садитесь из положения лёжа.", "Appears twice with slightly different Russian — merged"),
        e("To roll over", "Перевернуться / повернуться на бок", "Roll over onto your left side.", "Перевернитесь на левый бок."),
        e("To lean on / lean back", "Прислониться к / откинуться назад", "Lean back gently and let the chair support you.", "Аккуратно откиньтесь назад и опритесь на спинку кресла.", "Merged: 'lean back' (2x) and 'lean on'"),
        e("To crawl / on all fours", "Ползти / на четвереньках", "Get on all fours and slowly extend one arm forward.", "Встаньте на четвереньки и медленно вытяните одну руку вперёд.", "Merged: 'to crawl', 'on all fours', 'crawling on all fours'"),
        e("To take steps / toddle", "Делать шаги / топать", "Try to take three steps toward the parallel bars.", "Постарайтесь сделать три шага к брусьям.", "Merged: 'to take steps' and 'to toddle'"),
        e("To climb", "Забираться / подниматься", "Can you climb the stairs on your own?", "Вы можете самостоятельно подняться по лестнице?"),
        e("To reach", "Тянуться / дотянуться", "Try to reach the shelf without twisting your spine.", "Постарайтесь дотянуться до полки, не скручивая позвоночник."),
        e("To grab", "Схватывать / брать", "Grab the rail with your stronger hand first.", "Сначала возьмитесь за поручень более сильной рукой."),
        e("To lift", "Поднимать", "Lift your leg slowly to about forty-five degrees.", "Медленно поднимите ногу примерно на сорок пять градусов."),
        e("To bend", "Сгибать / наклоняться", "Bend the knee until you feel a gentle stretch.", "Согните колено до лёгкого ощущения растяжения.", "Merged: 'to bend' and 'to bend forward or backward' and 'to bend down'"),
        e("To bend at the waist", "Наклониться в пояснице", "Try not to bend at the waist — hinge at the hips instead.", "Старайтесь не наклоняться в пояснице — делайте наклон в тазобедренных суставах.", "Source: 'наклопяться в поясницы' — corrected"),
        e("To stretch", "Растягиваться / тянуться", "Stretch your arms above your head and hold for ten seconds.", "Потянитесь руками над головой и удерживайте десять секунд."),
        e("To balance", "Удерживать равновесие", "Try to balance on one foot for ten seconds.", "Постарайтесь удержать равновесие на одной ноге десять секунд."),
        e("To point", "Указывать / вытянуть", "Point your toes forward and hold.", "Вытяните носки вперёд и удерживайте."),
        e("To pinch", "Ущипнуть / щипать", "Pinch the clothespin to strengthen your grip.", "Сожмите прищепку, чтобы укрепить хват."),
        e("To squat", "Приседать", "Squat slowly and keep your back straight.", "Медленно приседайте, держа спину прямо.", "Source: 'приседать ; to squad' — typo in English corrected"),
        e("Flex a tendon", "Сгибать / задействовать сухожилие", "Flex the tendon by curling the toes downward.", "Согните сухожилие, загибая пальцы ног вниз."),
        e("Shift the weight", "Смещать вес", "Shift your weight onto your stronger leg first.", "Сначала сместите вес на более сильную ногу."),
        e("Scoop legs to the side of the bed", "Перенести ноги к краю кровати", "Scoop your legs to the side of the bed before standing up.", "Перенесите ноги к краю кровати, прежде чем вставать."),
        e("To wrap / guide the foot", "Завернуть / направлять ногу", "I will guide your foot through the movement.", "Я буду направлять вашу ногу во время движения.", "Merged: 'to wrap the foot' and 'to guide the foot'"),
        e("Turn the foot outward / inward", "Повернуть ногу наружу / внутрь", "Turn the foot outward, then inward, and hold each position.", "Поверните ногу наружу, затем внутрь, удерживая каждое положение."),
        e("Push off the chair", "Оттолкнуться от стула / встать со стула", "Push off the chair using both armrests to stand up.", "Оттолкнитесь от стула обеими руками, опираясь на подлокотники."),
        e("Crossed arms or legs (avoid)", "Скрещенные руки или ноги (избегать)", "Avoid crossing your arms or legs after hip replacement surgery.", "После операции по замене тазобедренного сустава избегайте скрещивания ног."),
        e("To boost in the bed", "Подтянуть в кровати", "We will boost you up in the bed so you are properly positioned.", "Мы подтянем вас в кровати, чтобы вы заняли правильное положение."),
        e("Warm-up / to get acclimated", "Разминка / привыкание к нагрузке", "We will start with a warm-up before the main exercises.", "Мы начнём с разминки перед основными упражнениями.", "Merged: 'to warm up legs' and 'to get acclimated'"),
        e("Twisting", "Скручивание / торсия", "Avoid twisting movements until the spine is stable.", "Избегайте скручиваний до стабилизации позвоночника."),
        e("Exercise load / intensity (нагрузка)", "Нагрузка (физическая)", "We will increase the exercise load gradually each week.", "Мы будем постепенно увеличивать нагрузку каждую неделю.", "Source: 'нагрузка' (no English given) — term added"),
        e("Do not overdo it", "Не перенапрягайтесь", "Push yourself, but do not overdo it — stop if there is sharp pain.", "Старайтесь, но не перенапрягайтесь — остановитесь при острой боли."),
        e("Steps machine / stair stepper", "Лестничный тренажёр", "The steps machine simulates climbing stairs for cardio training.", "Лестничный тренажёр имитирует подъём по лестнице для кардионагрузки."),
        # ── SENSORY / REHABILITATION ─────────────────────────────
        e("Desensitization", "Десенсибилизация / снижение чувствительности", "Desensitization therapy helps the residual limb tolerate touch.", "Десенсибилизация помогает остаточной конечности привыкнуть к прикосновениям."),
        e("To tap / tapping", "Постукивать / похлопывать", "Gently tap the sensitive area to begin desensitization.", "Осторожно постукивайте по чувствительному участку для десенсибилизации."),
        e("Limb wrapping", "Бинтование конечности", "Limb wrapping after amputation helps shape the residual limb.", "Бинтование конечности после ампутации помогает придать форму остаточной конечности."),
        # ── ADL AND SELF-CARE ────────────────────────────────────
        e("Bathing (ADL)", "Купание / гигиенические процедуры", "The OT assessed how safely she can manage bathing on her own.", "Эрготерапевт оценил, насколько безопасно она справляется с гигиеническими процедурами самостоятельно.", "From Others section; ADL = activity of daily living"),
        e("Grooming (ADL)", "Уход за собой (личная гигиена)", "Grooming tasks like brushing teeth and combing hair are part of the OT assessment.", "Уход за собой — чистка зубов и расчёсывание — входит в оценку эрготерапевта.", "From Others section"),
        e("Fine motor skills", "Навыки мелкой моторики", "The child is working on fine motor skills like buttoning and writing.", "Ребёнок работает над навыками мелкой моторики: застёгиванием пуговиц и письмом.", "From Others section; source: 'Fine Motor Sckill' — typo corrected"),
        e("Daily activity (ADL)", "Ежедневная деятельность / повседневные занятия", "Our goal is to help you return to your daily activities.", "Наша цель — помочь вам вернуться к ежедневной деятельности.", "From Others section"),
        e("Occupational therapy", "Эрготерапия", "Occupational therapy focuses on restoring independence in daily tasks.", "Эрготерапия направлена на восстановление самостоятельности в повседневных задачах.", "From Others section"),
        e("Bed rest", "Постельный режим", "The doctor recommends bed rest for the first two weeks.", "Врач рекомендует постельный режим в первые две недели.", "Merged: 'bed rest' and 'to be on bed rest'; from Others section"),
        e("With minimal assistance", "При минимальном содействии", "She can now transfer to the chair with minimal assistance.", "Сейчас она может пересесть на стул при минимальном содействии.", "From Others section"),
        e("Strenuous activity", "Интенсивная физическая нагрузка", "Avoid strenuous activity for at least six weeks after surgery.", "Избегайте интенсивной физической нагрузки не менее шести недель после операции.", "From Others section"),
        e("At their own pace", "В своём темпе", "Let the patient move at their own pace — do not rush them.", "Позвольте пациенту двигаться в своём темпе — не торопите.", "From Others section"),
        e("Precautions / home precautions", "Меры предосторожности (в домашних условиях)", "Review all precautions before the patient is discharged.", "Перед выпиской повторите все меры предосторожности.", "Merged: 'precautions' and 'precautions for home'"),
        # ── HEALTHCARE ROLES ─────────────────────────────────────
        e("Orthopedist", "Ортопед", "The orthopedist reviewed the X-rays and recommended surgery.", "Ортопед изучил рентгенограммы и рекомендовал операцию.", "From Others section"),
        e("Speech language pathologist (SLP)", "Специалист по патологии речи / логопед", "The SLP will evaluate swallowing and speech after the stroke.", "Специалист по патологии речи оценит глотание и речь после инсульта.", "Source: 'специалист по потологии речи' — corrected"),
        e("Spine team", "Команда специалистов по лечению позвоночника", "The spine team will review your case at the next meeting.", "Команда специалистов по позвоночнику рассмотрит ваш случай на следующем совещании.", "From Others section"),
        e("Assistive technology evaluator", "Специалист по оценке вспомогательных технологий", "The assistive technology evaluator will assess what devices can support you at home.", "Специалист по вспомогательным технологиям оценит, какие устройства помогут вам дома.", "From Others section"),
        e("Patient care assistant (PCA)", "Ассистент по уходу за пациентами / помощник по уходу", "The PCA will help you with transfers and personal care.", "Ассистент по уходу поможет вам с перемещением и личной гигиеной.", "From Others section"),
    ]
}

files = {
    "anatomy.json": anatomy,
    "conditions.json": conditions,
    "devices.json": devices,
    "pharmacology.json": pharmacology,
    "procedures.json": procedures,
}

for fname, data in files.items():
    path = os.path.join(OUTDIR, fname)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
    print(f"{fname} → {len(data['terms'])} terms")
